"""
Synthetic (NOT real proprietary data) refinery crude-blending LP/MILP
generator, for the SIH industrial case study.

Models: multiple crude types with availability, a set of blended products
with yields per crude, product demand ranges, a simple sulfur-quality
blending constraint, and a production-capacity limit, minimizing net
cost (crude purchase cost minus product revenue).

All numbers are illustrative/representative, generated by a fixed-seed
RNG for reproducibility, and are explicitly NOT real refinery data.
"""
from __future__ import annotations
import random
from sovereign_opt.core.model import Model, Sense, ObjSense, VarType


def generate_refinery_instance(n_crudes: int, n_products: int, seed: int = 42,
                                integer_batches: bool = False, batch_unit: float = 1.0) -> Model:
    """
    Decision variables: blend_{crude}_{product} = volume (kbbl) of crude
    routed to product's blend pool.

    Constraints:
      - crude availability: sum over products of blend_c_p <= availability_c
      - product demand:     sum over crudes of blend_c_p in [demand_lo_p, demand_hi_p]
      - sulfur quality:     weighted average sulfur_c <= max_sulfur_p  (linearized)
      - capacity:           total throughput <= plant_capacity

    Objective: minimize sum(cost_c * blend_c_p) - sum(price_p * output_p)
    i.e. minimize net cost of the blend plan.
    """
    rng = random.Random(seed)
    crudes = [f"crude{i+1}" for i in range(n_crudes)]
    products = [f"product{j+1}" for j in range(n_products)]

    availability = {c: round(rng.uniform(200, 900), 1) for c in crudes}
    cost = {c: round(rng.uniform(40, 90), 2) for c in crudes}
    sulfur = {c: round(rng.uniform(0.1, 3.0), 3) for c in crudes}

    demand_lo = {p: round(rng.uniform(80, 200), 1) for p in products}
    demand_hi = {p: round(demand_lo[p] + rng.uniform(50, 300), 1) for p in products}
    price = {p: round(rng.uniform(95, 160), 2) for p in products}
    max_sulfur = {p: round(rng.uniform(0.5, 2.0), 3) for p in products}

    plant_capacity = round(sum(availability.values()) * rng.uniform(0.55, 0.8), 1)

    if integer_batches and batch_unit != 1.0:
        # Discretize into "batches" of size batch_unit so integer domains are
        # small enough for this prototype's unaccelerated branch-and-bound
        # to actually reach proven optimality in reasonable time -- this is
        # an intentional demo-scale choice, not a solver capability claim.
        for c in crudes:
            availability[c] = round(availability[c] / batch_unit)
        for p in products:
            demand_lo[p] = round(demand_lo[p] / batch_unit)
            demand_hi[p] = round(demand_hi[p] / batch_unit)
        plant_capacity = round(plant_capacity / batch_unit)
        for c in crudes:
            cost[c] = cost[c] * batch_unit
        for p in products:
            price[p] = price[p] * batch_unit

    vtype = VarType.INTEGER if integer_batches else VarType.CONTINUOUS
    m = Model(name=f"refinery_{n_crudes}c_{n_products}p")

    blend_vars = {}
    for c in crudes:
        for p in products:
            vn = f"blend_{c}_{p}"
            ub = availability[c]
            m.add_variable(vn, lb=0, ub=ub, vtype=vtype)
            blend_vars[(c, p)] = vn

    obj = {}
    for (c, p), vn in blend_vars.items():
        obj[vn] = obj.get(vn, 0.0) + cost[c] - price[p]
    m.set_objective(obj, ObjSense.MIN)

    for c in crudes:
        m.add_constraint(f"avail_{c}", {blend_vars[(c, p)]: 1.0 for p in products}, Sense.LE, availability[c])

    for p in products:
        coeffs = {blend_vars[(c, p)]: 1.0 for c in crudes}
        m.add_constraint(f"demand_lo_{p}", coeffs, Sense.GE, demand_lo[p])
        m.add_constraint(f"demand_hi_{p}", coeffs, Sense.LE, demand_hi[p])

    # linearized sulfur quality constraint: sum_c (sulfur_c - max_sulfur_p) * blend_c_p <= 0
    for p in products:
        coeffs = {blend_vars[(c, p)]: (sulfur[c] - max_sulfur[p]) for c in crudes}
        m.add_constraint(f"sulfur_{p}", coeffs, Sense.LE, 0.0)

    all_vars = {vn: 1.0 for vn in blend_vars.values()}
    m.add_constraint("plant_capacity", all_vars, Sense.LE, plant_capacity)

    return m


INSTANCE_SIZES = {
    "small": dict(n_crudes=3, n_products=2),
    "medium": dict(n_crudes=6, n_products=4),
    "large": dict(n_crudes=12, n_products=8),
}
