"""
Builds SIH2026119.pptx -- the Smart India Hackathon 2026 submission deck for
Problem Statement 26119.

Six slides, official SIH structure, 13.333 x 7.5in.
Palette: white, black, graphite. No accent colour, by request.

EVERY number that appears in this deck comes from a result file in results/
or from the test suite. Nothing is hand-typed from memory and nothing is
rounded in a favourable direction. The figures embedded on slides 3 and 4 are
generated by scripts/make_deck_figures.py from the same CSVs.

Run: ./venv/bin/python scripts/build_sih_deck.py
"""
from __future__ import annotations
import os, sys

sys.path.insert(0, os.path.dirname(__file__))
from deck_canvas import (Canvas, to_pptx, to_preview, text_height,
                         W, H, INK, GRAPHITE, MID, HAIR, WASH, PALE, WHITE, BLUE,
                         FONT, MONO)

ROOT = os.path.join(os.path.dirname(__file__), "..")
SUMM = os.path.join(ROOT, "results", "summaries")
OUT_PPTX = os.path.join(ROOT, "SIH2026119.pptx")

ML = 0.62                 # left margin
MR = W - 0.62             # right margin
CW = MR - ML              # content width
CAP_Y = 6.96              # caption hairline
NAME = "SANKHYA"


def img_size(path, width):
    """Height in inches that preserves the PNG's aspect at the given width."""
    os.environ.setdefault("MPLCONFIGDIR", os.environ.get("TMPDIR", "/tmp") + "/mplcache")
    import matplotlib.image as mpimg
    im = mpimg.imread(path)
    return width * (im.shape[0] / im.shape[1])


def heading(cv, title, right=""):
    cv.text(ML, 0.36, 8.5, title, size=24, c=INK, bold=True)
    if right:
        cv.text(MR - 6.0, 0.54, 6.0, right, size=8.2, c=MID, align="r")
    cv.line(ML, 0.99, MR, 0.99, c=INK, lw=1.0)


def caption(cv, num, sentence):
    cv.line(ML, CAP_Y, MR, CAP_Y, c=HAIR, lw=0.7)
    cv.text(ML, 7.05, 0.5, num, size=8.4, c=INK, bold=True)
    cv.text(ML + 0.42, 7.05, 8.8, sentence, size=8.2, c=GRAPHITE)
    cv.text(MR - 4.2, 7.05, 4.2, f"Smart India Hackathon 2026  ·  PS 26119  ·  {NAME}",
            size=7.6, c=MID, align="r")


def panel_items(cv, x, y, w, items, size=8.3, c=INK, lead=1.44):
    cv.text(x, y, w, "\n".join("—   " + i for i in items), size=size, c=c, lead=lead)


# ===========================================================================
# SLIDE 1 -- Title page (official SIH field layout)
# ===========================================================================
def slide1():
    cv = Canvas()
    cv.text(ML, 0.40, 6.0, "SMART INDIA HACKATHON 2026", size=10, c=GRAPHITE, bold=True)
    cv.text(MR - 5.0, 0.42, 5.0, "Idea / Approach submission", size=9, c=MID, align="r")
    cv.line(ML, 0.80, MR, 0.80, c=INK, lw=1.0)

    fields = [
        ("Problem Statement ID", "26119", 14, 1.26),
        ("Problem Statement Title",
         "Indigenous GPU-Accelerated Optimization Solver —\n"
         "a Sovereign Alternative to IBM ILOG CPLEX / Gurobi / FICO Xpress", 13, 2.06),
        ("Theme", "______________________________", 14, 3.12),
        ("PS Category", "Software", 14, 3.92),
        ("Team ID", "______________________________", 14, 4.72),
        ("Team Name (Registered on portal)", "______________________________", 14, 5.52),
    ]
    for label, value, vsize, y in fields:
        cv.text(ML, y, 6.5, label, size=10, c=GRAPHITE)
        cv.text(ML, y + 0.23, 6.6, value, size=vsize, c=INK, bold=True, lead=1.26)

    # ---- right: a plain LP geometry motif (no stock art, no icons) --------
    ox, oy = 8.35, 5.30                      # axis origin
    cv.line(ox, 1.85, ox, oy, c=GRAPHITE, lw=0.9)
    cv.line(ox, oy, 12.35, oy, c=GRAPHITE, lw=0.9)
    cv.text(12.40, oy - 0.10, 0.4, "x1", size=8.5, c=MID)
    cv.text(ox - 0.34, 1.80, 0.4, "x2", size=8.5, c=MID)

    poly = [(ox, oy), (ox, 3.35), (9.25, 2.45), (10.85, 2.80), (11.70, oy)]
    cv.poly(poly, fill=WASH, edge=INK, lw=1.0)

    for dy, x2, y2 in ((0.00, 10.90, 3.405), (0.55, 11.20, 4.12), (1.10, 11.45, 4.81)):
        cv.line(8.45, 2.055 + dy, x2, y2, c=MID, lw=0.7, dash=True)

    cv.dot(9.25, 2.45, 0.062, fill=INK)
    cv.text(9.42, 2.24, 1.6, "x*", size=11.5, c=INK, bold=True)
    cv.text(9.42, 2.46, 2.2, "optimal vertex", size=7.8, c=GRAPHITE)

    cv.text(7.60, 5.58, 5.11, "minimise   c · x        subject to    A x  ≤  b ,    x  ≥  0",
            size=10.5, c=INK, align="c")
    cv.text(7.60, 5.92, 5.11,
            "The simplex method walks the vertices of this polytope to an optimum.\n"
            "Everything that does the walking here — the pivoting, the basis solves,\n"
            "the branch-and-bound tree above it — is our own code.",
            size=8.0, c=GRAPHITE, align="c", lead=1.34)

    cv.line(ML, 6.40, ML + 3.6, 6.40, c=INK, lw=1.0)
    cv.text(ML, 6.50, 5.0, NAME, size=16, c=INK, bold=True)
    cv.text(ML, 6.76, 6.0, "Sovereign Algorithmic Numerical Kernel", size=8.2, c=GRAPHITE)

    caption(cv, "01", "A from-scratch LP, MILP and QP solver core — the solver itself is the deliverable.")
    return cv


# ===========================================================================
# SLIDE 2 -- Proposed Solution
# ===========================================================================
def slide2():
    cv = Canvas()
    heading(cv, "Proposed Solution", "What we are building, and what is already working")

    # ---- name block ------------------------------------------------------
    cv.text(ML, 1.10, 4.5, NAME, size=33, c=INK, bold=True)
    cv.text(ML, 1.74, 4.45,
            "Sovereign Algorithmic Numerical Kernel —\nHybrid · Yield-verified · Auditable",
            size=8.4, c=GRAPHITE, lead=1.30)
    cv.text(ML, 2.10, 4.45,
            "sankhya (Sanskrit): number, enumeration — which is\n"
            "what the core actually does: enumerate vertices with\n"
            "the simplex, enumerate integer points with branch\n"
            "and bound.",
            size=7.9, c=MID, lead=1.32)

    # ---- what it is ------------------------------------------------------
    cv.text(5.30, 1.10, 7.41, "What we are building", size=10, c=INK, bold=True)
    cv.text(5.30, 1.34, 7.41,
            "A mathematical optimization solver core, written from the algorithms upward. The solver is\n"
            "the product; the modelling layer stays deliberately thin — a CLI, an MPS reader, a small API.\n"
            "\n"
            "No external optimization solver is called anywhere inside it: not CPLEX, Gurobi, Xpress,\n"
            "HiGHS, CBC, GLPK, SCIP, OR-Tools, PuLP, Pyomo, CVXPY or scipy.optimize. Even the linear\n"
            "algebra is ours — every basis solve is hand-written Gaussian elimination with partial\n"
            "pivoting, not a library call. numpy stores arrays; it never solves the problem.",
            size=8.8, c=INK, lead=1.34)

    cv.rect(5.30, 2.52, 7.41, 0.36, fill=WASH, edge=None)
    cv.text(5.44, 2.61, 7.15,
            "The gap is not modelling tools. It is that the solver core underneath every one of them is foreign.",
            size=9.0, c=INK, bold=True)

    # ---- architecture pipeline ------------------------------------------
    cv.text(ML, 3.02, 6.0, "Solver architecture", size=9.5, c=INK, bold=True)
    stages = [
        ("MODEL", "LP · MILP · QP\nvariables, bounds,\nrows, objective\nMPS file or API", "normal", None),
        ("PRESOLVE", "row and column\nreductions,\nfully reversible\nby postsolve", "normal", None),
        ("SOLVER CORE", "two-phase revised\nsimplex (Bland)\nbranch and bound\nQP layer: next", "solid", None),
        ("NUMERICAL ENGINE", "basis solves,\nequilibration,\npivot tolerances,\nfactorization", "normal", None),
        ("ACCELERATION", "sparse kernels,\nparallel vector ops,\nGPU where profiling\nshows a benefit", "dashed", "BUILD NEXT"),
        ("OUTPUT", "status, objective,\nsolution vector,\nMIP gap, runtime,\nverification, log", "normal", None),
    ]
    bw, gap, by, bh = 1.90, 0.13, 3.26, 1.20
    for i, (title, sub, kind, tag) in enumerate(stages):
        bx = ML + i * (bw + gap)
        if kind == "solid":
            cv.rect(bx, by, bw, bh, fill=INK, edge=INK)
            tc, sc = WHITE, "D8DADD"
        elif kind == "dashed":
            cv.rect(bx, by, bw, bh, fill=WHITE, edge=GRAPHITE, dash=True, lw=0.9)
            tc, sc = GRAPHITE, MID
        else:
            cv.rect(bx, by, bw, bh, fill=WASH, edge=HAIR)
            tc, sc = INK, GRAPHITE
        cv.text(bx, by + 0.11, bw, title, size=9.0, c=tc, bold=True, align="c")
        cv.text(bx + 0.08, by + 0.36, bw - 0.16, sub, size=7.1, c=sc, align="c", lead=1.32)
        if tag:
            cv.text(bx, by + bh - 0.20, bw, tag, size=6.6, c=GRAPHITE, bold=True, align="c")
        if i < len(stages) - 1:
            cv.chevron(bx + bw + gap / 2, by + bh / 2)

    # ---- validated now vs build next ------------------------------------
    pw = 5.92
    cv.rect(ML, 4.66, 0.115, 0.115, fill=INK, edge=None)
    cv.text(ML + 0.20, 4.63, pw, "VALIDATED NOW — implemented, tested and reproducible in the repository",
            size=8.8, c=INK, bold=True)
    panel_items(cv, ML, 4.90, pw, [
        "Two-phase revised simplex, Bland's rule, our own Gaussian-elimination basis solves",
        "Reversible presolve and postsolve",
        "Branch and bound MILP built on our own LP relaxations",
        "Automatic matrix equilibration recovers ill-conditioned models",
        "Independent verification of every reported solution",
        "MPS input, benchmark runner, exact rational optimality oracle",
    ])

    rx = 6.79
    cv.rect(rx, 4.66, 0.115, 0.115, fill=None, edge=GRAPHITE, lw=0.9)
    cv.text(rx + 0.20, 4.63, pw, "BUILD NEXT — designed, not yet built, and not claimed as working",
            size=8.8, c=GRAPHITE, bold=True)
    panel_items(cv, rx, 4.90, pw, [
        "QP layer: convex quadratic objective on the same numerical engine",
        "Sparse LU factorization with product-form updates",
        "Bounded-variable simplex; dual simplex and warm starts",
        "Cutting planes, pseudocost branching, primal heuristics",
        "GPU kernels for the numerical hot path",
        "Netlib / MIPLIB validation and a reference-solver comparison",
    ], c=GRAPHITE)

    # ---- what is different about it -------------------------------------
    cv.line(ML, 6.14, MR, 6.14, c=HAIR, lw=0.7)
    innov = [
        ("From-scratch solver core", "Simplex, branch and bound and every\nbasis solve are our own code."),
        ("Numerical transparency", "Pivot rules, tolerances and scaling\nare visible and changeable."),
        ("Selective acceleration", "GPU aimed at a profiled bottleneck,\nnot at the whole solver."),
        ("Industrial model focus", "Built against refinery blending and\nscheduling structure."),
        ("Verifiable output", "Every solution is re-checked by code\nthat did not produce it."),
    ]
    iw = (CW - 4 * 0.12) / 5
    for i, (t, s) in enumerate(innov):
        ix = ML + i * (iw + 0.12)
        cv.text(ix, 6.26, iw, t, size=8.6, c=INK, bold=True)
        cv.text(ix, 6.44, iw, s, size=7.2, c=GRAPHITE, lead=1.30)

    caption(cv, "02", "The solver core is the product — the modelling layer stays thin on purpose.")
    return cv


# ===========================================================================
# SLIDE 3 -- Technical Approach
# ===========================================================================
def slide3():
    cv = Canvas()
    heading(cv, "Technical Approach", "Methodology  ·  selective acceleration  ·  what makes the output trustworthy")

    # ---- solve path rail -------------------------------------------------
    cv.text(ML, 1.08, 6.0, "How a model is actually solved", size=9.5, c=INK, bold=True)
    nodes = [
        ("MODEL", "rows, columns,\nbounds, objective"),
        ("PRESOLVE", "reduce and record,\nreversibly"),
        ("NUMERICAL CORE", "basis solves,\nscaling, tolerances"),
        ("OPTIMIZATION", "simplex pivots,\nB&B tree search"),
        ("ACCELERATION", "kernel level\n(build next)"),
        ("VERIFY", "independent\nre-check"),
        ("RESULT", "status, objective,\ngap, solver log"),
    ]
    rail_y = 1.60
    step = CW / len(nodes)
    cx = [ML + step * (i + 0.5) for i in range(len(nodes))]
    cv.line(cx[0], rail_y, cx[-1], rail_y, c=HAIR, lw=0.8)
    for i, (t, s) in enumerate(nodes):
        sq = 0.115
        filled = (t != "ACCELERATION")
        cv.rect(cx[i] - sq, rail_y - sq, 2 * sq, 2 * sq,
                fill=INK if filled else WHITE, edge=INK if filled else GRAPHITE,
                dash=not filled, lw=0.9)
        cv.text(cx[i] - step / 2, rail_y + 0.22, step, t, size=8.2, c=INK, bold=True, align="c")
        cv.text(cx[i] - step / 2, rail_y + 0.39, step, s, size=7.0, c=GRAPHITE, align="c", lead=1.30)

    # feedback loop: VERIFY -> NUMERICAL CORE
    fy = 2.34
    cv.line(cx[5], rail_y + 0.66, cx[5], fy, c=GRAPHITE, lw=0.8)
    cv.line(cx[5], fy, cx[2], fy, c=GRAPHITE, lw=0.8)
    cv.line(cx[2], fy, cx[2], rail_y + 0.66, c=GRAPHITE, lw=0.8)
    cv.poly([(cx[2] - 0.055, rail_y + 0.78), (cx[2] + 0.055, rail_y + 0.78),
             (cx[2], rail_y + 0.66)], fill=GRAPHITE, edge=None)
    cv.text(cx[2], fy + 0.05, cx[5] - cx[2],
            "numerical failure or a badly conditioned basis  →  re-scale, re-factorize, re-solve",
            size=7.5, c=GRAPHITE, align="c")

    # ---- measured hotspot ------------------------------------------------
    cv.text(ML, 2.80, 6.2, "Where the time actually goes — measured, not assumed",
            size=9.5, c=INK, bold=True)
    hp = os.path.join(SUMM, "fig_hotspot.png")
    hw = 5.95
    cv.img(hp, ML, 3.02, hw, img_size(hp, hw))
    cv.text(ML, 3.02 + img_size(hp, hw) + 0.08, 6.20,
            "98.6% of solve time on refinery_lp_large (96 variables) is inside our own\n"
            "Gaussian elimination. cProfile and direct instrumentation were run separately\n"
            "and agree to 0.3 percentage points. Presolve, pivot selection, the ratio test\n"
            "and verification together are the other 1.4%.\n"
            "\n"
            "That one number decides the acceleration plan. There is a single hot path, and\n"
            "its first fix is sparse LU with factorization updates on the CPU — not a GPU.\n"
            "At this size the basis is tens of rows: far too small to pay for a transfer.",
            size=8.2, c=INK, lead=1.34)

    # ---- selective acceleration -----------------------------------------
    rx, rw = 7.05, 5.66
    cv.text(rx, 2.80, rw, "Selective acceleration — what runs where", size=9.5, c=INK, bold=True)
    bars = [
        ("CPU — control flow", "model parsing · presolve · pivot selection · branch decisions · tree management", "normal"),
        ("NUMERICAL KERNELS — the hot path", "basis factorization · triangular solves · sparse mat-vec · vector updates", "solid"),
        ("GPU — candidate, never the default", "only kernels large enough to amortise transfer, chosen by profiling", "dashed"),
        ("CPU — results", "incumbent bookkeeping · independent verification · solution, gap and log", "normal"),
    ]
    for i, (t, s, kind) in enumerate(bars):
        y = 3.04 + i * 0.50
        if kind == "solid":
            cv.rect(rx, y, rw, 0.44, fill=INK, edge=INK)
            tc, sc = WHITE, "D8DADD"
        elif kind == "dashed":
            cv.rect(rx, y, rw, 0.44, fill=WHITE, edge=GRAPHITE, dash=True, lw=0.9)
            tc, sc = GRAPHITE, MID
        else:
            cv.rect(rx, y, rw, 0.44, fill=WASH, edge=HAIR)
            tc, sc = INK, GRAPHITE
        cv.text(rx + 0.14, y + 0.06, rw - 0.28, t, size=8.4, c=tc, bold=True)
        cv.text(rx + 0.14, y + 0.24, rw - 0.28, s, size=7.1, c=sc)
        if i < len(bars) - 1:
            cv.chevron(rx + rw / 2, y + 0.47, size=0.055)

    cv.rect(rx, 5.14, rw, 0.62, fill=WASH, edge=None)
    cv.text(rx + 0.14, 5.22, rw - 0.28,
            "GPU acceleration is applied to measurable numerical\nbottlenecks, not forced onto irregular solver logic.",
            size=8.8, c=INK, bold=True, lead=1.30)
    cv.text(rx + 0.14, 5.56, rw - 0.28,
            "No GPU experiment has been run. No GPU speedup is claimed anywhere.",
            size=7.4, c=GRAPHITE)

    # ---- trust ----------------------------------------------------------
    cv.line(ML, 5.92, MR, 5.92, c=HAIR, lw=0.7)
    cv.text(ML, 6.02, 7.0, "Three checks that make the output trustworthy", size=9.5, c=INK, bold=True)
    checks = [
        ("Independent verification",
         "Every reported solution is re-checked against\nthe original model from raw coefficients, by\ncode separate from the solver. If it fails, the\nstatus is NUMERICAL_FAILURE, never OPTIMAL."),
        ("Sound optimality claims",
         "No path may report OPTIMAL, a 0% gap or\nINFEASIBLE unless it was actually proven. An\naudit found two paths that did; both are fixed\nand locked by tests."),
        ("Exact rational oracle",
         "Declared optima are re-derived in exact Fraction\narithmetic — Cramer's rule for LP, exhaustive\nenumeration for MILP — sharing no code and no\nfloating point with the simplex. 8/8 confirmed."),
    ]
    ccw = (CW - 2 * 0.22) / 3
    for i, (t, s) in enumerate(checks):
        x = ML + i * (ccw + 0.22)
        cv.text(x, 6.26, ccw, t, size=8.5, c=INK, bold=True)
        cv.text(x, 6.44, ccw, s, size=7.5, c=GRAPHITE, lead=1.28)

    caption(cv, "03", "Acceleration follows a measurement: 98.6% of solve time is in our own basis solves.")
    return cv


# ===========================================================================
# SLIDE 4 -- Feasibility and Viability
# ===========================================================================
def slide4():
    cv = Canvas()
    heading(cv, "Feasibility and Viability", "What is already validated  ·  what is still hard  ·  what comes next")

    # ---- evidence band ---------------------------------------------------
    cv.rect(ML, 1.08, CW, 0.86, fill=WASH, edge=None)
    metrics = [
        ("60", "tests passed\n0 failed, 0 skipped"),
        ("15", "benchmark instances\nrun end to end"),
        ("14", "solved OPTIMAL\nand verified"),
        ("1", "correctly detected\nINFEASIBLE"),
        ("8/8", "known optima matched\nby an exact oracle"),
        ("0", "numerical failures\n0 exceptions"),
    ]
    mw = CW / 6
    for i, (n, lab) in enumerate(metrics):
        x = ML + i * mw
        if i:
            cv.line(x, 1.16, x, 1.86, c=HAIR, lw=0.7)
        cv.text(x, 1.16, mw, n, size=23, c=INK, bold=True, align="c")
        cv.text(x, 1.58, mw, lab, size=7.3, c=GRAPHITE, align="c", lead=1.30)

    # ---- representative results -----------------------------------------
    cv.text(ML, 2.10, 6.6, "Three representative results", size=9.5, c=INK, bold=True)
    cols = [("Instance", 2.15), ("What it is", 1.45), ("Result", 2.15), ("Time", 0.80)]
    tx, ty = ML, 2.34
    cv.rect(tx, ty, sum(c[1] for c in cols), 0.24, fill=PALE, edge=None)
    cxp = tx
    for name, cwd in cols:
        cv.text(cxp + 0.06, ty + 0.06, cwd, name, size=7.6, c=INK, bold=True)
        cxp += cwd
    rows = [
        ("refinery_lp_large", "96 vars, 37 rows\nsynthetic refinery LP",
         "OPTIMAL\n674 simplex iterations", "1.6652 s"),
        ("refinery_milp_small_batches", "6 vars, 10 rows\ninteger batch sizes",
         "OPTIMAL\n15 B&B nodes, 0.0000% gap", "0.0378 s"),
        ("lp_ill_conditioned_1e12", "coefficient spread\nof 1e12",
         "NUMERICAL_FAILURE without scaling\nOPTIMAL with auto scaling", "0.0002 s"),
    ]
    for r, row in enumerate(rows):
        ry = ty + 0.24 + r * 0.46
        cv.line(tx, ry + 0.46, tx + sum(c[1] for c in cols), ry + 0.46, c=HAIR, lw=0.6)
        cxp = tx
        for ci, cell in enumerate(row):
            cv.text(cxp + 0.06, ry + 0.09, cols[ci][1] - 0.10, cell,
                    size=7.5, c=INK if ci in (0, 3) else GRAPHITE,
                    bold=(ci == 0), lead=1.30)
            cxp += cols[ci][1]
    sp = os.path.join(SUMM, "fig_scaling.png")
    sw = 5.36
    cv.img(sp, 7.35, 2.26, sw, img_size(sp, sw))
    cv.text(7.35, 2.10, sw, "Measured cost of the current basis solve", size=9.5, c=INK, bold=True)

    # ---- risks -----------------------------------------------------------
    cv.text(ML, 4.42, 8.0, "Risks we can already name, and what we do about them",
            size=9.5, c=INK, bold=True)
    rcols = [("Risk", 2.30), ("Why it matters", 4.40), ("What we do about it", 5.393)]
    ry0 = 4.66
    cv.rect(ML, ry0, CW, 0.22, fill=PALE, edge=None)
    cxp = ML
    for name, cwd in rcols:
        cv.text(cxp + 0.06, ry0 + 0.05, cwd, name, size=7.6, c=INK, bold=True)
        cxp += cwd
    risks = [
        ("Numerical instability",
         "A badly scaled basis makes an absolute pivot tolerance\nmeaningless; the solver can return a confident wrong answer.",
         "Automatic equilibration, shipped and measured. Independent verification\ndowngrades anything it cannot confirm to NUMERICAL_FAILURE."),
        ("Search explosion on MILP",
         "Branch and bound is exponential. On wide integer domains it\nruns out of nodes before it proves anything.",
         "Node and time limits, and a status that refuses to say OPTIMAL over a tree\nwe did not finish. Measured: 0.49% gap left after 5000 nodes, published."),
        ("Scale — dense basis re-solve",
         "Rebuilding and re-solving the basis every iteration is O(m³).\nAt 96 variables that is 1.67 s; industrial sizes will not finish.",
         "Sparse LU with factorization updates is Stage 2, and the 98.6% profile says\nit is the right target. No large-scale claim until it is measured."),
        ("GPU overhead",
         "Small kernels lose more to host-device transfer than they gain.\nA GPU port done for its own sake would be slower, not faster.",
         "Profile first, CPU sparse LU second, GPU only where a measurement justifies\nit — and no GPU claim of any kind in the meantime."),
    ]
    for i, row in enumerate(risks):
        yy = ry0 + 0.22 + i * 0.38
        cv.line(ML, yy + 0.38, MR, yy + 0.38, c=HAIR, lw=0.6)
        cxp = ML
        for ci, cell in enumerate(row):
            cv.text(cxp + 0.06, yy + 0.06, rcols[ci][1] - 0.12, cell,
                    size=7.2, c=INK if ci == 0 else GRAPHITE,
                    bold=(ci == 0), lead=1.30)
            cxp += rcols[ci][1]

    # ---- roadmap ---------------------------------------------------------
    stages = [
        ("Stage 1 — Prototype core", "done: LP, MILP, presolve, verification", True),
        ("Stage 2 — Numerical performance", "sparse LU, factorization updates, bounds", False),
        ("Stage 3 — Optimization strength", "dual simplex, warm starts, cuts, branching", False),
        ("Stage 4 — Acceleration", "parallel kernels; GPU where profiling justifies", False),
        ("Stage 5 — External validation", "Netlib, MIPLIB, reference-solver comparison", False),
    ]
    sw2 = (CW - 4 * 0.10) / 5
    for i, (t, s, done) in enumerate(stages):
        x = ML + i * (sw2 + 0.10)
        cv.rect(x, 6.44, sw2, 0.42, fill=INK if done else WHITE,
                edge=INK if done else HAIR, dash=False)
        cv.text(x + 0.10, 6.50, sw2 - 0.20, t, size=7.7, c=WHITE if done else INK, bold=True)
        cv.text(x + 0.10, 6.66, sw2 - 0.20, s, size=6.8, c="D8DADD" if done else GRAPHITE)

    caption(cv, "04", "Stages carry no dates on purpose — each one is gated on a measured result, not a calendar.")
    return cv


# ===========================================================================
# SLIDE 5 -- Impact and Benefits
# ===========================================================================
def slide5():
    cv = Canvas()
    heading(cv, "Impact and Benefits", "What changes when the solver core is ours")

    # ---- before / after --------------------------------------------------
    lw_, rw_ = 5.35, 5.66
    cv.rect(ML, 1.14, lw_, 1.98, fill=WASH, edge=HAIR)
    cv.text(ML + 0.16, 1.24, lw_ - 0.3, "Today — the core is foreign", size=9.4, c=GRAPHITE, bold=True)
    panel_items(cv, ML + 0.16, 1.48, lw_ - 0.32, [
        "The solver core is foreign, commercial and closed",
        "Licences renew for as long as the models are used",
        "Internal algorithms cannot be inspected or changed",
        "Numerical behaviour cannot be tuned when a model misbehaves",
        "Sensitive industrial models are built inside external tooling",
        "Domestic capability stops at the modelling layer",
    ], size=8.0, c=GRAPHITE, lead=1.42)

    cv.arrow_h(6.18, 6.92, 2.13, c=INK, lw=1.4, head=0.13)

    cv.rect(7.05, 1.14, rw_, 1.98, fill=WHITE, edge=INK, lw=1.1)
    cv.text(7.21, 1.24, rw_ - 0.3, "With a sovereign solver core", size=9.4, c=INK, bold=True)
    panel_items(cv, 7.21, 1.48, rw_ - 0.32, [
        "The solver core is ours: simplex, branch and bound, basis solves",
        "Runs locally and offline; no external optimization engine in the loop",
        "Every algorithm is readable, testable and modifiable",
        "The numerical layer can be changed for the models that need it",
        "Models stay inside the organisation that owns them",
        "One core serves refinery, power, logistics and manufacturing",
    ], size=8.0, c=INK, lead=1.42)

    cv.text(ML, 3.22, CW,
            "No rupee saving and no percentage cost reduction appears anywhere on this slide, because neither has been measured. "
            "The benefit being claimed is control over the solver core.",
            size=7.8, c=MID)

    # ---- why sovereign ---------------------------------------------------
    cv.text(ML, 3.58, 6.1, "Why sovereign, specifically", size=9.5, c=INK, bold=True)
    ccols = [("", 2.25), ("Commercial solver", 1.85), ("Our solver core", 1.95)]
    cy0 = 3.82
    cv.rect(ML, cy0, 6.05, 0.24, fill=PALE, edge=None)
    cxp = ML
    for name, cwd in ccols:
        cv.text(cxp + 0.06, cy0 + 0.06, cwd, name, size=7.6, c=INK, bold=True)
        cxp += cwd
    crows = [
        ("Solver internals", "closed", "open, in this repository"),
        ("Modifiability", "not available", "any layer, including the pivot rule"),
        ("Deployment control", "vendor terms", "local, offline, ours"),
        ("Algorithm visibility", "documented behaviour", "source, tests, measured results"),
        ("Model ownership", "tied to vendor tooling", "plain files, our own reader"),
        ("Domestic extensibility", "none", "the entire point of the project"),
    ]
    for i, row in enumerate(crows):
        yy = cy0 + 0.24 + i * 0.28
        cv.line(ML, yy + 0.28, ML + 6.05, yy + 0.28, c=HAIR, lw=0.6)
        cxp = ML
        for ci, cell in enumerate(row):
            cv.text(cxp + 0.06, yy + 0.07, ccols[ci][1] - 0.10, cell, size=7.5,
                    c=INK if ci != 1 else GRAPHITE, bold=(ci == 0))
            cxp += ccols[ci][1]
    cv.text(ML, 5.84, 6.05,
            "This is a claim about control and inspectability, not about speed. Commercial solvers are\n"
            "mature, fast and very well engineered — which is exactly why owning a core of our own\n"
            "matters, and why no performance comparison against them appears anywhere in this deck.",
            size=7.4, c=MID, lead=1.32)

    # ---- synthetic refinery ---------------------------------------------
    rx = 6.95
    cv.text(rx, 3.58, 5.76, "Synthetic refinery case study", size=9.5, c=INK, bold=True)
    for i, nm in enumerate(("Crude C1", "Crude C2", "Crude C3")):
        yy = 3.88 + i * 0.40
        cv.rect(rx, yy, 1.05, 0.30, fill=WASH, edge=HAIR)
        cv.text(rx, yy + 0.09, 1.05, nm, size=7.6, c=INK, align="c")
        cv.line(rx + 1.05, yy + 0.15, 8.24, yy + 0.15, c=GRAPHITE, lw=0.7)
    cv.line(8.24, 4.03, 8.24, 4.83, c=GRAPHITE, lw=0.7)
    cv.arrow_h(8.24, 8.48, 4.43, c=GRAPHITE, lw=0.9, head=0.09)

    cv.rect(8.50, 4.06, 1.42, 0.76, fill=INK, edge=INK)
    cv.text(8.50, 4.22, 1.42, "BLENDING\nand yields", size=7.8, c=WHITE, bold=True, align="c", lead=1.30)

    cv.arrow_h(9.92, 10.14, 4.43, c=GRAPHITE, lw=0.9, head=0.09)
    cv.line(10.14, 4.03, 10.14, 4.83, c=GRAPHITE, lw=0.7)
    for i, nm in enumerate(("Petrol", "Diesel", "ATF")):
        yy = 3.88 + i * 0.40
        cv.rect(10.40, yy, 1.10, 0.30, fill=WASH, edge=HAIR)
        cv.text(10.40, yy + 0.09, 1.10, nm, size=7.6, c=INK, align="c")
        cv.line(10.14, yy + 0.15, 10.40, yy + 0.15, c=GRAPHITE, lw=0.7)

    cv.text(rx, 5.16, 5.76,
            "Constraints:  crude availability · plant capacity · product demand range ·\n"
            "sulfur quality limit · material balance\n"
            "Objective:  minimise blending cost, equivalently maximise margin",
            size=7.6, c=GRAPHITE, lead=1.34)

    cv.rect(rx, 5.66, 5.76, 0.72, fill=WASH, edge=None)
    cv.text(rx + 0.14, 5.74, 5.48,
            "Largest instance solved: 96 variables, 37 constraints — OPTIMAL in 1.6652 s,\n"
            "674 simplex iterations, independently verified. Integer batch variant: OPTIMAL\n"
            "in 15 branch-and-bound nodes with a 0.0000% gap, in 0.0378 s.",
            size=7.8, c=INK, lead=1.32)
    cv.text(rx, 6.48, 5.76,
            "Synthetic case study. The structure is realistic — crudes, yields, quality limits, demand\n"
            "ranges — but the data is generated by industrial/refinery.py. No real plant's proprietary\n"
            "model was used or solved.",
            size=7.2, c=MID, lead=1.30)

    caption(cv, "05", "The claim is control over the solver core, not a cost number we have not measured.")
    return cv


# ===========================================================================
# SLIDE 6 -- Research and References
# ===========================================================================
def slide6():
    cv = Canvas()
    heading(cv, "Research and References", "Every source below was checked before it was listed")

    cv.text(ML, 1.08, 7.0, "The methods we implemented, and where they come from",
            size=9.5, c=INK, bold=True)
    refs = (
        "Dantzig, G. B. — Linear Programming and Extensions. Princeton University Press, 1963.\n"
        "Implemented: the simplex method, in its revised two-phase form.\n"
        "\n"
        "Bland, R. G. — New finite pivoting rules for the simplex method. Mathematics of Operations\n"
        "Research 2(2), 1977.   Implemented: the anti-cycling pivot rule used in both phases.\n"
        "\n"
        "Land, A. H. and Doig, A. G. — An automatic method of solving discrete programming problems.\n"
        "Econometrica 28(3), 1960.   Implemented: branch and bound over our own LP relaxations.\n"
        "\n"
        "Curtis, A. R. and Reid, J. K. — On the automatic scaling of matrices for Gaussian elimination.\n"
        "IMA Journal of Applied Mathematics 10(1), 118–124, 1972.   Implemented: row and column\n"
        "equilibration, with power-of-two factors so scaling introduces no error of its own.\n"
        "\n"
        "Bartels, R. H. and Golub, G. H. — The simplex method of linear programming using LU\n"
        "decomposition. Communications of the ACM 12(5), 1969.   Stage 2. Not yet built.\n"
        "\n"
        "Forrest, J. J. H. and Tomlin, J. A. — Updated triangular factors of the basis to maintain sparsity\n"
        "in the product form simplex method. Mathematical Programming 2, 1972.   Stage 2, not yet\n"
        "built: these are the factorization updates that would remove our measured 98.6% hot path.\n"
        "\n"
        "Applegate, D., Díaz, M., Hinder, O., Lu, H., Lubin, M., O'Donoghue, B. and Schudy, W. —\n"
        "Practical Large-Scale Linear Programming using Primal-Dual Hybrid Gradient. NeurIPS 2021\n"
        "(arXiv:2106.04756).   Why large LPs parallelise through first-order methods.\n"
        "\n"
        "Lu, H., Yang, J., Hu, H., Huangfu, Q., Liu, J., Liu, T., Ye, Y., Zhang, C. and Ge, D. — cuPDLP-C:\n"
        "A Strengthened Implementation of cuPDLP for Linear Programming by C language.\n"
        "arXiv:2312.14832, 2023.   Evidence that GPU linear programming works through first-order\n"
        "methods rather than a GPU simplex — which is why our GPU stage targets kernels, not pivots.\n"
        "\n"
        "Stage 5 validation targets: Netlib LP (netlib.org/lp), MIPLIB 2017 (miplib.zib.de), Mittelmann\n"
        "benchmarks (plato.asu.edu/bench.html). None has been run: this build environment has no\n"
        "general internet access, so nothing in the repository is labelled as Netlib or MIPLIB data."
    )
    cv.text(ML, 1.32, 7.05, refs, size=7.7, c=GRAPHITE, lead=1.30)

    cv.line(ML, 5.98, ML + 7.05, 5.98, c=HAIR, lw=0.7)
    cv.text(ML, 6.08, 7.05, "What a judge can run, in this repository", size=9.0, c=INK, bold=True)
    cv.text(ML, 6.28, 7.05,
            "./run_demo.sh — tests, an LP solve, an MILP solve, the full 15-instance benchmark, the\n"
            "scaling A/B and the plots, in one command.\n"
            "python3 scripts/verify_known_optima.py — re-derives every declared optimum in exact\n"
            "rational arithmetic, with no simplex involved.\n"
            "python3 scripts/profile_hotspots.py — reproduces the 98.6% measurement that this deck's\n"
            "acceleration plan rests on.",
            size=7.5, c=GRAPHITE, lead=1.32)

    # ---- closing proposition --------------------------------------------
    bx, bw = 7.90, 4.81
    cv.rect(bx, 1.32, bw, 3.30, fill=WHITE, edge=INK, lw=1.2)
    cv.text(bx + 0.30, 1.78, bw - 0.6,
            "A sovereign optimization\nengine, built from the\nmathematical core upward.",
            size=15, c=INK, bold=True, align="c", lead=1.32)
    cv.line(bx + 1.55, 2.82, bx + bw - 1.55, 2.82, c=HAIR, lw=0.8)
    cv.text(bx + 0.20, 3.00, bw - 0.4, "Model   →   Solve   →   Accelerate   →   Verify",
            size=10, c=GRAPHITE, align="c")
    cv.text(bx + 0.20, 3.44, bw - 0.4, "LP      ·      MILP      ·      QP",
            size=15, c=INK, bold=True, align="c")
    cv.text(bx + 0.20, 3.78, bw - 0.4,
            "LP and MILP are implemented and validated.\nQP is the next layer, and is not built yet.",
            size=7.6, c=MID, align="c", lead=1.30)
    cv.text(bx + 0.20, 4.22, bw - 0.4,
            "Open architecture  ·  Local control  ·  Inspectable algorithms",
            size=9.2, c=INK, align="c")

    cv.text(bx, 4.92, bw, NAME, size=20, c=INK, bold=True, align="c")
    cv.text(bx, 5.28, bw, "Sovereign Algorithmic Numerical Kernel", size=8.2, c=GRAPHITE, align="c")
    cv.text(bx, 5.52, bw, "Smart India Hackathon 2026  ·  Problem Statement 26119",
            size=8.0, c=MID, align="c")

    caption(cv, "06", "Every source here was checked, and everything not yet done is listed as not yet done.")

    # ===========================================================================
    # SLIDE 7 -- Technical Methodology
    # ===========================================================================
    def slide7():
        cv = Canvas()
        heading(cv, "TARK | Technical Methodology", "Indigenous Optimization Solver  ·  SIH 2026  ·  PS 26119")

        def node(x, y, w, h, title, body, fill=WASH, edge=HAIR, title_color=INK,
               body_color=GRAPHITE, strong=False, dashed=False):
           cv.rect(x, y, w, h, fill=fill, edge=edge, lw=1.1 if strong else 0.8,
                 dash=dashed, rounded=True)
           cv.text(x + 0.10, y + 0.12, w - 0.20, title, size=9.0 if strong else 8.0,
                 c=title_color, bold=True, align="c", lead=1.12)
           cv.text(x + 0.10, y + (0.39 if strong else 0.34), w - 0.20, body,
                 size=6.8, c=body_color, align="c", lead=1.20)

        def flow(x1, x2, y, c=BLUE, lw=1.0, head=0.09):
           cv.arrow_h(x1, x2, y, c=c, lw=lw, head=head)

        cv.text(ML, 1.12, 4.5, "MAIN SOLVE PATH", size=8.8, c=BLUE, bold=True)
        cv.text(MR - 3.8, 1.12, 3.8, "from model to an independently checked answer",
              size=7.6, c=MID, align="r")

        y, h = 1.43, 0.88
        nodes = [
           (ML, 1.55, "Industrial\nOptimization Model", "LP / MILP", WASH, BLUE, True),
           (2.30, 1.58, "Model Parser\n& Validation", "MPS / structured\nmodel input", WASH, INK, False),
           (4.07, 1.58, "Presolve", "Remove redundant constraints\nTighten bounds · simplify", WASH, INK, False),
           (5.84, 1.58, "Numerical\nConditioning", "Automatic matrix equilibration\nDetect ill-conditioning", WASH, INK, False),
           (7.61, 2.12, "LP Solver Core", "Two-Phase Revised Simplex\nBasis management · pivot selection\nNumerical linear algebra", "E8F0F7", BLUE, True),
        ]
        for x, w, title, body, fill, color, strong in nodes:
           node(x, y, w, h, title, body, fill=fill, edge=color, title_color=color,
               strong=strong)
        for x1, x2 in [(2.17, 2.30), (3.88, 4.07), (5.65, 5.84), (7.42, 7.61)]:
           flow(x1, x2, y + h / 2)

        # MILP branch: the split is explicit, while the LP path remains visible.
        split_x, split_y = 8.67, 2.47
        cv.line(split_x, y + h, split_x, split_y, c=BLUE, lw=1.0)
        cv.line(split_x, split_y, split_x, 2.78, c=BLUE, lw=1.0)
        cv.dot(split_x, split_y, 0.045, fill=BLUE)
        cv.text(8.76, 2.18, 1.0, "MILP path", size=6.8, c=BLUE, bold=True)
        node(7.72, 2.78, 1.78, 0.76, "LP Relaxation", "continuous bound",
            fill=WASH, edge=BLUE, title_color=BLUE)
        node(9.84, 2.78, 1.78, 0.76, "Branch & Bound", "Node selection · branching\nBounds · incumbent update",
            fill="E8F0F7", edge=BLUE, title_color=BLUE, strong=True)
        node(11.96, 2.78, 0.75, 0.76, "Optimality /\nTermination", "proof or limit",
            fill=WASH, edge=BLUE, title_color=BLUE)
        flow(9.50, 9.84, 3.16)
        flow(11.62, 11.96, 3.16)

        # LP models take the direct route to termination; MILP models use the branch.
        cv.line(9.73, y + h / 2, 9.73, 2.48, c=BLUE, lw=1.0)
        cv.line(9.73, 2.48, 12.33, 2.48, c=BLUE, lw=1.0)
        cv.line(12.33, 2.48, 12.33, 2.78, c=BLUE, lw=1.0)
        cv.poly([(12.33, 2.48), (12.24, 2.42), (12.24, 2.54)], fill=BLUE, edge=None)
        cv.text(10.08, 2.22, 2.0, "LP path", size=6.8, c=BLUE, bold=True)

        # Converged verification path.
        cv.line(12.33, 3.54, 12.33, 4.05, c=BLUE, lw=1.0)
        node(8.30, 4.12, 3.02, 0.78, "Independent Verification",
            "Feasibility · constraints · objective\nInteger feasibility", fill="E8F0F7",
            edge=BLUE, title_color=BLUE, strong=True)
        cv.line(12.33, 4.05, 11.32, 4.05, c=BLUE, lw=1.0)
        cv.poly([(11.32, 4.05), (11.22, 3.98), (11.22, 4.12)], fill=BLUE, edge=None)
        node(8.30, 5.14, 3.02, 0.68, "Verified Solution",
            "Optimal  ·  Infeasible  ·  Limit Reached", fill=BLUE, edge=BLUE,
            title_color=WHITE, body_color=WHITE, strong=True)
        cv.line(9.81, 4.90, 9.81, 5.14, c=BLUE, lw=1.0)
        cv.poly([(9.81, 5.14), (9.73, 5.03), (9.89, 5.03)], fill=BLUE, edge=None)

        # Separate lower lane: explicitly future work, visually subordinate.
        cv.line(ML, 6.00, MR, 6.00, c=HAIR, lw=0.7)
        cv.text(ML, 6.13, 2.8, "DEVELOPMENT ROADMAP", size=8.8, c=GRAPHITE, bold=True)
        cv.text(ML + 2.95, 6.13, 6.2,
              "Performance & Future Acceleration  ·  not currently implemented",
              size=7.6, c=MID)
        roadmap = [
           (ML, 1.65, "Profiling", "identify bottlenecks"),
           (2.55, 1.65, "Sparse Linear Algebra", "factorization + basis updates"),
           (4.95, 1.65, "Parallel Computation", "multi-core execution"),
           (7.35, 1.65, "GPU Acceleration", "CUDA kernels for suitable workloads"),
        ]
        for i, (x, w, title, body) in enumerate(roadmap):
           node(x, 6.38, w, 0.43, title, body, fill=WHITE, edge=MID,
               title_color=GRAPHITE, body_color=MID, dashed=True)
           if i < len(roadmap) - 1:
              flow(x + w, roadmap[i + 1][0], 6.60, c=MID, lw=0.8, head=0.07)

        caption(cv, "07", "TARK develops the optimization engine itself: parse, solve, branch, verify.")
        return cv

    globals()["slide7"] = slide7
    return cv


def main():
    slide6_spec = slide6()
    slide7_fn = globals()["slide7"]
    slides = [slide1(), slide2(), slide3(), slide4(), slide5(), slide6_spec,
              slide7_fn()]
    if "--preview" in sys.argv:
        for p in to_preview(slides, os.path.join(SUMM, "deck_preview")):
            print("[preview]", os.path.relpath(p, ROOT))
    else:
        to_pptx(slides, OUT_PPTX)
        print("[saved]", os.path.relpath(OUT_PPTX, ROOT))
        for p in to_preview(slides, os.path.join(SUMM, "deck_preview")):
            print("[preview]", os.path.relpath(p, ROOT))


if __name__ == "__main__":
    main()
